module Constants
  VAT_RATE               = 0.125
  SHIPPING_AMOUNT        = 89.0
  DEFAULT_PAYMENT_METHOD = 'cod'
  REFUND_MAXIMUM_DAY_CRITERIA = 7.days
  MINIMUM_ORDER_QUANTITY = 100 # grams

  MAX_QUANTITY_PIECES = 100
  MAX_QUANTITY_GRAMS  = 1000
end
